theme: jekyll-theme-cayman
title: Eric Odongo's homepage
description: This is my persoal website that provides a summary of my work experiences, 
             key academic milestones, and my side projects that I am working on.